### ISSUE TITLE
problem in material default values

### ISSUE THREAD

**Issue by joelvbernier** [HEXRD/hexrd#154]
@saransh13 -- getting a `AttributeError` when attempting to use the `material.load_materials_hdf5` method.  Looks like the default value for the `kev` kwarg is a float instead of a `valWUnits` instance?  This seems to be a fairly pervasive problem, so we may need to take a look at catching all the parameters you intend to be `valWUnits` in the `__init__()` method and the various property getters/setters.

```
 ml = material.load_materials_hdf5('C:/Users/berni/Downloads/materials.h5', dmin=0.7)
Traceback (most recent call last):

  File "<ipython-input-33-7b6b13461239>", line 1, in <module>
    ml = material.load_materials_hdf5('C:/Users/berni/Downloads/materials.h5', dmin=0.7)

  File "c:\users\berni\onedrive\documents\github\hexrd\hexrd\material.py", line 731, in load_materials_hdf5
    return {

  File "c:\users\berni\onedrive\documents\github\hexrd\hexrd\material.py", line 732, in <dictcomp>
    name: Material(name, f, dmin=dmin, kev=kev, sgsetting=sgsetting)

  File "c:\users\berni\onedrive\documents\github\hexrd\hexrd\material.py", line 171, in __init__
    self._dmin.getVal('nm'), self._beamEnergy.value,

AttributeError: 'float' object has no attribute 'getVal'
```

**Comment by joelvbernier** [comment]
I'll add that when attempting to feed through floats in material, it should be assumed the units are
- radians for angles
- kev for energy
- &#8491;ngstroms for lengths
Of course, we should reflect this in the documentation.

**Comment by joelvbernier** [comment]
Looks like same goes for `dmin` kwarg...

**Comment by joelvbernier** [comment]
@saransh13 -- I think this is closed as well.  Can you link the relevant PR(s) and close it if so?  Thanks.
