### ISSUE TITLE
KeyError in CalcXRFormFactor

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#273]
On Linux, at least, for this attached [example.zip](https://github.com/HEXRD/hexrd/files/6556066/example.zip), if I run
`hexrd find-orientations mruby_config.yml`, I get a `KeyError` (attached below).

It looks like this is being caused by the `charge` variable being bytes instead of a string.
The check is essentially doing this:

```python
if b'0' == '0':
    ...
else:
    ...
```

At least on my system, `b'0' == '0'` returns `False`.

I guess a potentially good solution to this is to make sure that wherever the `charge` variable
gets set, that it is a string instead of bytes. Something like this:

```python
if isinstance(charge, (bytes, bytearray)):
    charge = charge.decode()
```

Full error is below:

```python
21-05-27 13:39:04 - === begin find-orientations ===
21-05-27 13:39:04 - "working_dir" not specified, defaulting to "/data/patrick/hexrd/hydra/example"
Traceback (most recent call last):
  File "/home/patrick/virtualenvs/hexrd/bin/hexrd", line 33, in <module>
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/cli/main.py", line 73, in main
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/cli/find_orientations.py", line 123, in execute
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/config/root.py", line 68, in analysis_id
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/config/root.py", line 57, in material
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/config/material.py", line 88, in beam_energy
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/config/material.py", line 39, in materials
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/material.py", line 975, in load_materials_hdf5
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/material.py", line 976, in <dictcomp>
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/material.py", line 201, in __init__
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/material.py", line 341, in update_structure_factor
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/unitcell.py", line 760, in CalcXRSF
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/unitcell.py", line 738, in CalcXRFormFactor
KeyError: "Ob'0'"
```

**Comment by joelvbernier** [comment]
This is on Ubutnu @psavery ?

**Comment by psavery** [comment]
> This is on Ubutnu @psavery ?

That's right.

**Comment by joelvbernier** [comment]
@psavery and @saransh13 -- did we fix this?

**Comment by saransh13** [comment]
Ok. I think the `charge` variable is byte because of HDF5 I/O. It was easier to write a vector of bytes in the file. Do you know how to write a vector of strings?
Alternatively, I can write them as integers and then append the `+` sign later.

**Comment by joelvbernier** [comment]
Can't we just modify the conditional to
```
if charge in ['0', b'0']:
    ...
else:
    ...
```

**Comment by psavery** [comment]
@saransh13 That change does indeed fix it. [See my comment on that branch](https://github.com/HEXRD/hexrd/commit/a9a42445d05f7b56d846b312ea5c1e8fd59dd74a#r52215516).

**Comment by joelvbernier** [comment]
Should we get the associated fix merged for this one @psavery?

**Comment by psavery** [comment]
Well, I've been the only one to run into the issue. But others may run into it in the future. I'd say we can get a fix merged.

**Comment by psavery** [comment]
Upon further inspection, it looks like this problem is caused by h5py making a backwards incompatible change starting in `h5py==3.0.0`. For `h5py<3.0.0`, string datatypes are returned as python `str` types. For `h5py>=3.0.0`, string datatypes are returned as python `bytes` types. Users who use `h5py>=3.0.0` will start running into this issue. See https://github.com/theislab/anndata/issues/442 for similar discussion.

We have also seen this issue in other places where strings are read from HDF5 files. For instance, in instrument `.hexrd` files, we have encountered the issue for the distortion key:
```python
Traceback (most recent call last):
  File "/home/brianna/.virtualenvs/hexrd/lib/python3.8/site-packages/hexrd/instrument.py", line 476, in __init__
    distortion = distortion_pkg.get_mapping(
  File "/home/brianna/.virtualenvs/hexrd/lib/python3.8/site-packages/hexrd/distortion/__init__.py", line 56, in get_mapping
    cls = Registry.distortion_registry[maptype]
KeyError: "b'GE_41RT'"
```

I think we can write a utility function for reading in strings/bytes from h5py datasets, something like this:
```python
def hdf5_read_string(dataset):
    string_dtype = h5py.check_string_dtype(dataset.dtype)
    if string_dtype is not None and string_dtype.encoding == 'utf-8':
        dataset = dataset.asstr()
    return dataset[()]
```

This will return bytes if the underlying data is bytes, and it will return strings if the underlying data is strings...

h5py used to do this for us automatically, but I guess not anymore...
