### ISSUE TITLE
Reading multiple .h5 files but only one detector is available.

### ISSUE THREAD

**Issue by georgejoe018** [HEXRD/hexrd#281]
I am using a linux installed version of HEXRD 0.8 and am not able to read multiple .h5 files. I can upload one file, read the file, and look at half of the detector data but not multiple files at once. I am also limited to only selecting "detector 1" instead of being able to select multiple detectors to create two detector graphs. The error I get when I try to read two files at once is as follows:

Traceback (most recent call last):
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/ui/async_worker.py", line 73, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/ui/image_load_manager.py", line 182, in process_ims
    ims = ImageFileManager().open_directory(dirs, self.files[i], options)
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/ui/image_file_manager.py", line 139, in open_directory
    ims = imageseries.open(temp.name, 'image-files')
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/imageseries/__init__.py", line 18, in open
    adapter = reg[format](filename, **kwargs)
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/imageseries/load/imagefiles.py", line 38, in __init__
    self._process_files()
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/imageseries/load/imagefiles.py", line 116, in _process_files
    info = FileInfo(imgf, **kw)
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/hexrd/imageseries/load/imagefiles.py", line 213, in __init__
    with fabio.open(filename) as img:
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/fabio/openimage.py", line 167, in openimage
    obj = obj.read(obj.filename, frame)
  File "/u/mx/fa/jgeorge1/.conda/envs/hexrd_test_2/lib/python3.8/site-packages/fabio/eigerimage.py", line 142, in read
    raise NotGoodReader("HDF5 file does not contain an Eiger-like structure.")
fabio.fabioutils.NotGoodReader: HDF5 file does not contain an Eiger-like structure.

I am not sure if it is the install or something on our end that is causing .h5 files to not be read for two separate detectors.

**Comment by joelvbernier** [comment]
@georgejoe018 -- I need a little clarification here.  Are you saying that the detector (singular) has more than one image file representing a single frame?  We load HDF5 images for our 2-detector (or 8, if we split them into 2x2 subpanels) dexela instrument at CHESS without issue.

**Comment by georgejoe018** [comment]
@joelvbernier -- When I load in a set of .h5 files, they come in pairs. For example, there could be a ff1.h5 and a ff2.h5 for a sample. They are supposed to be the 2-detector files where the first file is from one detector and the second file is from the second detector. The issue is that both files cannot be loaded into separate detectors but are both attributed to detector 1 instead of being assigned to their respective detectors.

**Comment by psavery** [comment]
@georgejoe018 In the left panel of the GUI, click on "Instrument Calibration" and "Form View". You can see a "Detector Parameters" section in there where you can add, remove, or rename detectors. Make sure there are two detectors in the drop-down menu. You can add a detector with the "+" sign.
![Screenshot from 2021-06-14 20-14-13](https://user-images.githubusercontent.com/9558430/121978150-36c52e00-cd4d-11eb-996f-59233720d1f9.png)

Then, when you open up the files via either "File"->"Open"->"Images" or "Load Data"->"Select Image Files", it should pop up a dialog similar to the one below, where you can indicate which file belongs to which detector.
![Screenshot from 2021-06-14 20-14-52](https://user-images.githubusercontent.com/9558430/121978280-80157d80-cd4d-11eb-836c-0e1e9623e524.png)

We should definitely add some documentation for things like this...

**Comment by joelvbernier** [comment]
In general @georgejoe018 you should _always_ start a session with the proper instrument config, which sets the mater table of detectors.  Then when loading images, it will either auto-associate (if the detector names are somewhere in the image filenames) or you can manually associate as @psavery shows above.  I am sorry if that was not clear.  We are populating the examples repo with more and more instruments as use cases pop up.  For the CHESS dexelas, there is already an example directory for indexing the NIST ruby standard [here](https://github.com/HEXRD/examples/tree/master/NIST_ruby/multiruby_dexelas/include).
