### ISSUE TITLE
Add "lmfit" to list of requirements

### ISSUE THREAD

**Issue by psavery** [HEXRD/hexrd#99]
```python
Traceback (most recent call last):
  File "example_LeBail.py", line 1, in <module>
    from hexrd.WPPF import Spectrum, LeBail, Rietveld#, LeBail_Asym, Rietveld_Asym, LeBail_FPA
  File "/home/patrick/virtualenvs/hexrd/src/hexrd/hexrd/WPPF.py", line 11, in <module>
    import lmfit
ModuleNotFoundError: No module named 'lmfit'
```

**Comment by saransh13** [comment]
one thing I want to note here that `lmfit1.0.1` has some strange behavior where the least square minimization routines don't work as expected. `lmfit1.0.0` does not have those issues and should be preferred.
